// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriverResultKind } from "./DriverResultKind.ts";
import type { RunId } from "./RunId.ts";

export type DriverResult = { runId: RunId, result: DriverResultKind, };
