// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriverErrorDetails } from "./DriverErrorDetails.ts";
import type { DriverSuccessDetails } from "./DriverSuccessDetails.ts";

export type DriverResultKind = { "error": DriverErrorDetails } | { "success": DriverSuccessDetails };
